$xelatex = 'xelatex -interaction=nonstopmode -file-line-error -synctex=1 %O %S';
$pdflatex = 'pdflatex -interaction=nonstopmode -file-line-error -synctex=1 %O %S';
$pdf_mode = 1;
$max_repeat = 5;
$silent = 0;

push @generated_exts, 'synctex.gz';
